Repository gardenlinux/builder, pull requests merged in 2023-06, with the labels that each got.

#3 add cli flag to specify target dir
  build
Labels: needs/review, size/xs

#5 removing builder-build from `build` and adding instructions how to build the builder
  Dockerfile
  README.md
  build
Labels: needs/changes, needs/review, size/xs

#9 using realpath instead of pwd in the build script
  build
Labels: needs/review, size/xs

#15 exporting keyring in asc format for apt/trusted.gpg.d directory
  builder/bootstrap
  pkg.list
Labels: kind/bug, needs/review, size/xs

#19 move mkdir of build directory before call to realpath
  build
Labels: needs/review, size/xs

#18 Fix #5
  README.md
  build
Labels: needs/review, size/xs

#20 feat: output pkg list manifest
  builder/image.manifest
  builder/make_get_artifact_rules
  builder/make_list_build_artifacts
Labels: needs/review, size/xs
